# fly.toml app configuration file generated for lockbox on 2025-10-26T11:40:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lockbox'
primary_region = 'iad'

[env]
  DB_FILE_NAME = "file:/litefs/lockbox.db"

[build]

[http_service]
  internal_port = 9090
  force_https = false
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"
